quarkus.application.name=java-transactional-outbox-worker
quarkus.http.port=8080
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=${CORS_ORIGINS:http://localhost:4200,http://localhost:8088}
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER:outbox}
%prod.quarkus.datasource.password=${DB_PASSWORD:outbox}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/outbox}
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-openapi.info-title=Transactional Outbox Worker API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.micrometer.export.prometheus.path=/q/metrics
%prod.quarkus.log.console.json.enabled=true
mp.messaging.outgoing.payment-events.connector=smallrye-kafka
mp.messaging.outgoing.payment-events.topic=payment-authorized
mp.messaging.outgoing.payment-events.key.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.outgoing.payment-events.value.serializer=org.apache.kafka.common.serialization.StringSerializer
mp.messaging.incoming.payment-events-evidence.connector=smallrye-kafka
mp.messaging.incoming.payment-events-evidence.topic=payment-authorized
mp.messaging.incoming.payment-events-evidence.group.id=outbox-evidence
mp.messaging.incoming.payment-events-evidence.auto.offset.reset=earliest
mp.messaging.incoming.payment-events-evidence.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
mp.messaging.incoming.payment-events-evidence.value.deserializer=org.apache.kafka.common.serialization.StringDeserializer
outbox.worker.batch-size=20
outbox.worker.lease-seconds=30
outbox.worker.max-attempts=5
outbox.worker.interval=1s

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=postgres:16.8
%test.quarkus.datasource.devservices.reuse=false
%test.quarkus.flyway.clean-at-start=true
%test.outbox.worker.interval=1s
