quarkus.application.name=java-transactional-outbox-worker
quarkus.http.port=8080
quarkus.datasource.db-kind=postgresql
%prod.quarkus.datasource.username=${DB_USER:outbox}
%prod.quarkus.datasource.password=${DB_PASSWORD:outbox}
%prod.quarkus.datasource.jdbc.url=${DB_URL:jdbc:postgresql://localhost:5432/outbox}
quarkus.flyway.migrate-at-start=true
quarkus.hibernate-orm.schema-management.strategy=validate
quarkus.hibernate-orm.log.sql=false
quarkus.smallrye-openapi.info-title=Transactional Outbox Worker API
quarkus.smallrye-openapi.info-version=1.0.0
quarkus.micrometer.export.prometheus.path=/q/metrics

%test.quarkus.datasource.devservices.enabled=true
%test.quarkus.datasource.devservices.image-name=postgres:16.8
%test.quarkus.datasource.devservices.reuse=false
%test.quarkus.flyway.clean-at-start=true
